[package]
name = "payments"
version = "0.1.0"
authors = ["Alessio Artoni <alessio@artoni.org>"]
edition = "2021"

[dependencies]
csv = "1.1"
rust_decimal = "1.23"
rust_decimal_macros = "1.23"
serde = { version = "1", features = ["derive"] }
